// <auto-generated />
using System;
using GrammarWorkbook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrammarWorkbook.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181220110834_XXX")]
    partial class XXX
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Dialog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DialogExerciseId");

                    b.Property<Guid?>("SentenceId");

                    b.HasKey("Id");

                    b.HasIndex("DialogExerciseId");

                    b.HasIndex("SentenceId");

                    b.ToTable("Dialog");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Title");

                    b.Property<Guid?>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Exercise");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Exercise");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DialogId");

                    b.Property<Guid?>("FillTheBlanksExerciseId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("DialogId");

                    b.HasIndex("FillTheBlanksExerciseId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Sentence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("FillTheBlanksExerciseId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("FillTheBlanksExerciseId");

                    b.ToTable("Sentence");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SubTitle");

                    b.Property<string>("Title");

                    b.Property<Guid?>("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.DialogExercise", b =>
                {
                    b.HasBaseType("GrammarWorkbook.Data.Models.Exercise");

                    b.HasDiscriminator().HasValue("dialogue");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.FillTheBlanksExercise", b =>
                {
                    b.HasBaseType("GrammarWorkbook.Data.Models.Exercise");

                    b.HasDiscriminator().HasValue("fill");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.MatchTheWordsExercise", b =>
                {
                    b.HasBaseType("GrammarWorkbook.Data.Models.Exercise");

                    b.HasDiscriminator().HasValue("match");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Dialog", b =>
                {
                    b.HasOne("GrammarWorkbook.Data.Models.DialogExercise")
                        .WithMany("Dialogs")
                        .HasForeignKey("DialogExerciseId");

                    b.HasOne("GrammarWorkbook.Data.Models.Sentence", "Sentence")
                        .WithMany()
                        .HasForeignKey("SentenceId");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Exercise", b =>
                {
                    b.HasOne("GrammarWorkbook.Data.Models.Topic")
                        .WithMany("Exercises")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Option", b =>
                {
                    b.HasOne("GrammarWorkbook.Data.Models.Dialog")
                        .WithMany("Options")
                        .HasForeignKey("DialogId");

                    b.HasOne("GrammarWorkbook.Data.Models.FillTheBlanksExercise")
                        .WithMany("Options")
                        .HasForeignKey("FillTheBlanksExerciseId");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Sentence", b =>
                {
                    b.HasOne("GrammarWorkbook.Data.Models.FillTheBlanksExercise")
                        .WithMany("Sentences")
                        .HasForeignKey("FillTheBlanksExerciseId");
                });

            modelBuilder.Entity("GrammarWorkbook.Data.Models.Topic", b =>
                {
                    b.HasOne("GrammarWorkbook.Data.Models.Unit")
                        .WithMany("Topics")
                        .HasForeignKey("UnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
